version: '2'

services:
  #ORG1
  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-channel-artifacts/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-channel-artifacts/809b4c2084823003b6ac6b9a8e0df71e6aaf58ec497984c7df411b5a3bfbf3c7_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-channel-artifacts/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-channel-artifacts/809b4c2084823003b6ac6b9a8e0df71e6aaf58ec497984c7df411b5a3bfbf3c7_sk -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-channel-artifacts
    container_name: ca_peerOrg1

  #ORG2
  ca2:
    image: hyperledger/fabric-ca
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-org2
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-channel-artifacts/ca.org2.example.com-cert.pem
    - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-channel-artifacts/674996c703d1220e37efb529ce6fa596b78305504e211d5d85ca890238afd394_sk
    ports:
    - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-channel-artifacts/ca.org2.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-channel-artifacts/674996c703d1220e37efb529ce6fa596b78305504e211d5d85ca890238afd394_sk -b admin:adminpw -d'
    volumes:
    - ../crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-channel-artifacts
    container_name: ca_peerOrg2

  #ORG3
  ca3:
    image: hyperledger/fabric-ca
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-org3
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-channel-artifacts/ca.org3.example.com-cert.pem
    - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-channel-artifacts/e22ff8e22c9a213eb0a783198ac1588318065b24171e1a4f913187c7926d7728_sk
    ports:
    - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-channel-artifacts/ca.org3.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-channel-artifacts/e22ff8e22c9a213eb0a783198ac1588318065b24171e1a4f913187c7926d7728_sk -b admin:adminpw -d'
    volumes:
    - ../crypto-config/peerOrganizations/org3.example.com/ca/:/etc/hyperledger/fabric-ca-server-channel-artifacts
    container_name: ca_peerOrg3

  zookeeper0:
    extends:
      file:   base/docker-compose-base.yaml
      service: zookeeper0
    container_name: zookeeper0

  zookeeper1:
    extends:
      file:   base/docker-compose-base.yaml
      service: zookeeper1
    container_name: zookeeper1

  kafka0:
    extends:
      file:   base/docker-compose-base.yaml
      service: kafka0
    container_name: kafka0
    depends_on:
      - zookeeper0
      - zookeeper1

  kafka1:
    extends:
      file:   base/docker-compose-base.yaml
      service: kafka1
    container_name: kafka1
    depends_on:
      - zookeeper0
      - zookeeper1

  orderer0.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer0.example.com
    container_name: orderer0.example.com
    depends_on:
      - kafka0
      - kafka1

  orderer1.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer1.example.com
    container_name: orderer1.example.com
    depends_on:
      - kafka0
      - kafka1

  #ORG1
  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.example.com

  #ORG2
  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.example.com

  #ORG3
  peer0.org3.example.com:
    container_name: peer0.org3.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org3.example.com